### PR TITLE
feat: enable secret injection in context 

### PR DESCRIPTION
**Pull request by musabmasood**
Signed-off-by: Musab Mirza musab@musabmasood.com 

Prefixing a value with `$` in the context will gets its value from the secret instead.

If the secret is:

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  bar: shhhh
```

And the cm is

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    hello: world
    cool: $pool
    foo: $bar
```

The context computed would be:

```
hello: world
cool: $pool # if the secret isn't found the value isn't replaced
foo: shhhh

```

### CODE REVIEW

**Comment by musabmasood** [comment]
@alexmt can I get your 👀  on this? Thanks

**Review by ryota-sakamoto — CHANGES_REQUESTED** [review]
@musabmasood

Thank you for contribution.
notifications-engine has same logic to replace the secret, so I think it is better to store this feature into notifications-engine rather than argocd-notifications.
https://github.com/argoproj/notifications-engine/blob/e8ac53e2f18eb747a7173f12c818bfc6182688bb/pkg/api/config.go#L141

**Comment by musabmasood** [comment]
@ryota-sakamoto got it. Do you want me to close this PR and open another one for notifications-engine? Or we need to have this in both?

**Comment by ryota-sakamoto** [comment]
@musabmasood 
Would you close this PR and open the new PR for notifications-engine?
And then you will finish this feature into notifications-engine, open PR in argocd-notifications to update library about notifications-engine.

**Comment by musabmasood** [comment]
Closing this one for now, will look into porting it to the notifications engine later.

**Comment by srkanpu** [comment]
@musabmasood Thank you for your contribution.  Is there an PR to update in notifications engine? Can you please share?

**Pull request closed without merging**
