### PR TITLE
feat: GetAppDetails function in templates/triggers

### PR DESCRIPTION
**Pull request by paydaycay**
Hi ! I suggest this PR to add function repo.GetAppDetails to templates/triggers to support loading application details.

Hope the code is clear enough because it's my first time in golang 

#150

### CODE REVIEW

**Comment by paydaycay** [comment]
Hi @alexmt I fixed the problem with the tests (sorry I didn't write test but I'm not comfortable enough with golang to write tests) but I don't know how to resolve the problem with golangci-lint. 
[Someone already encountered the problem](https://github.com/golangci/golangci-lint-action/issues/23) but I don't know if we are in same case.
Could you help me to fix this ?

**Comment by alexmt** [comment]
That looks very solid for a first contribution! Thank you @paydaycay ! looking

**Comment by alexmt** [comment]
Awesome! I have no comments for code, just formatting nitpicking. 

Can you please run this command to sort imports:

```
find . -name \*.go | xargs -I {} goimports -w {} 
```

and one more to regenerate mocks

```
make generate
```

**Comment by paydaycay** [comment]
Thanks @alexmt ! I hope it will be useful for the community. :) 
I ran the commands and pushed

**Review by alexmt — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
