### PR TITLE
fix annotations for tracking notifications have sent.

### PR DESCRIPTION
**Pull request by mayzhang2000**
fixes: #117

Here is the new format:
```
metadata:
  annotations:
    on-sync-succeeded.argocd-notifications.argoproj.io: |
      slack:general=2020-11-23T17:31:32-08:00
```

### CODE REVIEW

**Comment by alex1989hu** [comment]
I don't know will your PR fix or not, but the notification is not working after https://github.com/argoproj-labs/argocd-notifications/pull/116

**Comment by olegsu** [comment]
> I don't know will your PR fix or not, but the notification is not working after #116

@alex1989hu 
#116 was not released yet.
Did you install from upstream? What is the error you see?

**Comment by alex1989hu** [comment]
> > I don't know will your PR fix or not, but the notification is not working after #116
> 
> @alex1989hu
> #116 was not released yet.
> Did you install from upstream? What is the error you see?

I know it is not released; used the latest tag. Created a container with the state before #116 and it worked. 

Latest: There is no error message, just info level. Behaviour is different: the buggy one does not log anything about notification and template. Therefore, I do not get any email. Switch back to either v0.7.0 or the state before #116 => OK again.

**Review by alexmt — APPROVED** [review]
LGTM

**Pull request merged**
